device: cuda
training:
  batch_size: 16
  eval_batch_size: 16
  epochs: 30
  current_epoch: 0
  gpu_ids:
  - 0
  num_workers: 12
  lr: 0.0001
  optimizer: adamw
  clipping: true
  clipping_max_norm: 1.0
  scheduler: cosine
  warmup: false
  warmup_epochs: 4
  cyclic_period: 10
  plateau_patience: 3
  plateau_factor: 0.5
  seed: 42
  use_ema: false
  goal_mask_prob: 0
  modal_dropout_prob: 0
data:
  goal_condition: true
  normalize: true
  context_type: temporal
  target_observation_enable: true
  target_context: true
  context_size: 4
  distance:
    min_dist_cat: 0
    max_dist_cat: 12
  action:
    min_dist_cat: 3
    max_dist_cat: 10
  pred_horizon: 8
  action_horizon: 6
  learn_angle: true
  image_size:
  - 96
  - 96
  goal_type: image
  obs_type: image
  img_type: depth
log:
  project_folder: /home/roblab20/dev/pilot/pilot_bc/pilot_train/logs
  run_name: train_pilot_policy/${policy_model.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  num_images_log: 4
  print_log_freq: 75
  eval_log_freq: 3
  image_log_freq: 1
  eval_fraction: 0.25
  eval_freq: 1
  save_model_freq: 10
  wandb:
    run:
      enable: true
      name: ${log.run_name}
      log_freq: 10
    setup:
      project: pilot-release
      entity: nimrodcurtis
      mode: online
linear_encoder:
  name: tcn
  lin_features_dim: 3
  lin_encoding_size: 256
  kernel_size: 2
  drop_out: 0.2
vision_encoder:
  name: efficientnet
  version: efficientnet-b1
  in_channels: 1
  pretrained: false
  vision_encoding_size: 256
policy_model:
  name: pidiff
  mha_num_attention_heads: 4
  mha_num_attention_layers: 4
  mha_ff_dim_factor: 4
  down_dims:
  - 64
  - 128
  - 256
  cond_predict_scale: false
  noise_scheduler:
    type: ddpm
    num_diffusion_iters_eval: 10
    num_diffusion_iters_train: 100
    beta_schedule: squaredcos_cap_v2
datasets:
  data_folder: /home/roblab20/dev/pilot/pilot_bc/pilot_dataset/asher
  max_depth: 10000
  nimrod:
    end_slack: 0
    goals_per_obs: 1
    negative_mining: false
    number_of_bags: 42
    stats:
      max_ang_vel: 43.9604
      max_lin_vel: 2.0607
      mean_ang_vel: 0.0086
      mean_lin_vel: 0.2707
      min_ang_vel: -43.8578
      min_lin_vel: -1.6696
      std_ang_vel: 1.5666
      std_lin_vel: 0.4158
    test: /home/roblab20/dev/pilot/pilot_bc/pilot_train/dataset/asher/test/nimrod
    time: 24.011
    train: /home/roblab20/dev/pilot/pilot_bc/pilot_train/dataset/asher/train/nimrod
    waypoint_spacing: 2
  robots:
  - nimrod
