# bags_folder: "/home/roblab20/catkin_ws/src/zion_ros/zion_zed_ros_interface/bag"
destination_folder: "/home/roblab20/dev/pilot/pilot_bc/pilot_dataset/eval"
bags_folder: /media/roblab20/Expansion/pilot/test_easy
save_raw: true                        # I dont see a reason why to set it to false
mode: eval
force: false
nimrod:                               # dataset name
  aligned_topics: ["odom", "target_object", "goal_reach", "goal_pose"]     # pick topics to be aligned
  # sync_rate: 4                    # alignment rate, if null we will 
                                      # use the min frequency, from the aligned topics frequency
  save_vid: true                      # saving video
  pre_truncated: 0                    # number in seconds -> when to start storing data = 0 + pre_truncated.
                                    # usefull when standing few seconds at the begining. 
  post_truncated: 0                   # number in seconds -> when to finish storing data = end_time - post_truncated.
  max_depth: 9000