# bags_folder: "/home/roblab20/catkin_ws/src/zion_ros/zion_zed_ros_interface/bag"
bags_folder: "/media/roblab20/My\ Passport/bags_pilot"
destination_folder: "/home/roblab20/dev/pilot/pilot_bc/pilot_dataset/dataset"

save_raw: true                        # I dont see a reason why to set it to false

nimrod:                               # dataset name
  aligned_topics: ["odom", "rgb"]     # pick topics to be aligned
  sync_rate: 20                    # alignment rate, if null we will 
                                      # use the min frequency, from the aligned topics frequency
  save_vid: true                      # saving video

turtlebot: 
  aligned_topics: ["odom", "rgb"]     # pick topics to be aligned
  sync_rate: 20                    # alignment rate, if null we will 
                                      # use the min frequency, from the aligned topics frequency
  save_vid: true                      # saving video