config_path: "/home/roblab20/dev/pilot/pilot_bc/pilot_train/config/pilot.yaml"
model_path: "/home/roblab20/dev/pilot/pilot_bc/pilot_deploy/checkpoints/pilot-turtle-linefollow_2024_03_06_13_31_24/latest.pth"
device: cuda
wpt_id: 2
properties:
  max_lin_vel: 0.25 # [meter/sec]
  max_ang_vel: 2.8 # [rad/sec]
  frame_rate: 20 