training:
  goal_condition: false
  batch_size: 16
  eval_batch_size: 16
  epochs: 70
  current_epoch: 0
  gpu_ids:
  - 0
  num_workers: 12
  lr: 0.0001
  optimizer: adamw
  clipping: true
  clipping_max_norm: 1.0
  scheduler: cosine
  warmup: false
  warmup_epochs: 4
  cyclic_period: 10
  plateau_patience: 3
  plateau_factor: 0.5
  seed: 42
  alpha: 0.5
  beta: 10
  use_ema: false
  goal_mask_prob: 0.5
device: cuda
data:
  goal_condition: true
  normalize: true
  context_type: temporal
  target_observation_enable: true
  target_context: true
  context_size: 4
  distance:
    min_dist_cat: 0
    max_dist_cat: 20
  action:
    min_dist_cat: 3
    max_dist_cat: 20
  close_far_threshold: 30
  len_traj_pred: 8
  action_horizon: 6
  learn_angle: true
  image_size:
  - 96
  - 96
  goal_type: image
  obs_type: image
  img_type: depth
log:
  project_folder: /home/roblab20/dev/pilot/pilot_bc/pilot_train/logs
  run_name: train_pilot_policy/${policy_model.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  num_images_log: 4
  print_log_freq: 100
  eval_log_freq: 5
  image_log_freq: 2
  eval_fraction: 0.25
  eval_freq: 1
  save_model_freq: 10
  wandb:
    run:
      enable: true
      name: ${log.run_name}
      log_freq: 10
    setup:
      project: pilot-release
      entity: nimrodcurtis
      mode: online
encoder_model:
  name: efficientnet
  version: efficientnet-b1
  in_channels: 1
  pretrained: false
policy_model:
  name: pidiff
  mha_num_attention_heads: 4
  mha_num_attention_layers: 4
  mha_ff_dim_factor: 4
  late_fusion: false
  obs_encoding_size: 256
  lin_encoding_size: 256
  num_lin_features: 2
  down_dims:
  - 64
  - 128
  - 256
  cond_predict_scale: false
  noise_scheduler:
    type: ddpm
    num_diffusion_iters_eval: 10
    num_diffusion_iters_train: 70
    beta_schedule: squaredcos_cap_v2
datasets:
  data_folder: /home/roblab20/dev/pilot/pilot_bc/pilot_dataset/all
  max_depth: 5000
  nimrod:
    end_slack: 3
    goals_per_obs: 1
    negative_mining: false
    number_of_bags: 94
    stats:
      max_ang_vel: 1.2586
      max_lin_vel: 0.7718
      mean_ang_vel: -0.0076
      mean_lin_vel: 0.0158
      min_ang_vel: -1.141
      min_lin_vel: -0.8049
      std_ang_vel: 0.2114
      std_lin_vel: 0.1675
    test: /home/roblab20/dev/pilot/pilot_bc/pilot_train/dataset/all/test/nimrod
    time: 39.9132
    train: /home/roblab20/dev/pilot/pilot_bc/pilot_train/dataset/all/train/nimrod
    waypoint_spacing: 2
  robots:
  - nimrod
  - turtlebot
  turtlebot:
    end_slack: 3
    goals_per_obs: 1
    negative_mining: false
    number_of_bags: 94
    stats:
      max_ang_vel: 0.8625
      max_lin_vel: 0.3021
      mean_ang_vel: 0.0005
      mean_lin_vel: 0.0116
      min_ang_vel: -0.7804
      min_lin_vel: -0.3125
      std_ang_vel: 0.1682
      std_lin_vel: 0.085
    test: /home/roblab20/dev/pilot/pilot_bc/pilot_train/dataset/all/test/turtlebot
    time: 48.8943
    train: /home/roblab20/dev/pilot/pilot_bc/pilot_train/dataset/all/train/turtlebot
    waypoint_spacing: 2
